Fix log out bug in application.html.erb line 37. Remove import Rails... from application.js which was causing an 'Uncaught TypeError... Rails.start is not a function'. Removing the line fixed the drag and drop bug and the fade out bug where both did not work in last push.